# -*- coding: utf-8 -*-
"""Stutter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKRFojguoUACuDtZ55zp_uzaKLIXnHKl
"""

import pandas as pd
df = pd.read_csv("/content/updated_labels_with_clips.csv")
df.head()

df.info()

df.iloc[1]['FilePath']

df.columns

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchaudio
import pandas as pd
import numpy as np

class StutterDataset(Dataset):
    def __init__(self, csv_file, transform=None):
        self.data = pd.read_csv(csv_file)
        self.transform = transform
        self.mel_spec = torchaudio.transforms.MelSpectrogram(
            sample_rate=16000,
            n_fft=400,
            hop_length=160,
            n_mels=64
        )

        # Normalize label columns (excluding 'ClipId' and 'FilePath')
        label_columns = self.data.columns[2:]
        self.data[label_columns] = self.data[label_columns].apply(self.normalize_column)

    def normalize_column(self, column):
        min_val = column.min()
        max_val = column.max()
        if min_val == max_val:
            return column.apply(lambda x: 0 if pd.isna(x) else 1)
        return column.apply(lambda x: 0 if pd.isna(x) else (x - min_val) / (max_val - min_val))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        audio_path = self.data.iloc[idx]['FilePath']
        waveform, sample_rate = torchaudio.load(audio_path)

        # Convert to mono if stereo
        if waveform.shape[0] > 1:
            waveform = torch.mean(waveform, dim=0, keepdim=True)

        # Resample to a fixed sample rate (e.g., 16kHz)
        if sample_rate != 16000:
            waveform = torchaudio.transforms.Resample(sample_rate, 16000)(waveform)

        # Apply mel spectrogram transform
        mel_spec = self.mel_spec(waveform)

        # Convert to decibels
        mel_spec = torchaudio.transforms.AmplitudeToDB()(mel_spec)

        # Ensure fixed size (e.g., 64 mel bins, 1000 time steps)
        if mel_spec.shape[2] > 1000:
            mel_spec = mel_spec[:, :, :1000]
        else:
            mel_spec = torch.nn.functional.pad(mel_spec, (0, 1000 - mel_spec.shape[2]))

        # Get normalized labels (exclude 'ClipId' and 'FilePath')
        labels = torch.tensor(self.data.iloc[idx][2:].values.astype(np.float32))

        return mel_spec, labels

# 2. Model Architecture
class StutterDetectionModel(nn.Module):
    def __init__(self, num_labels):
        super(StutterDetectionModel, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(128 * 8 * 125, 512)  # Adjusted for 64 mel bins
        self.fc2 = nn.Linear(512, num_labels)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.pool(self.relu(self.conv3(x)))
        x = x.view(-1, 128 * 8 * 125)  # Adjusted for 64 mel bins
        x = self.relu(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

# 3. Training Pipeline
def train_model(model, train_loader, val_loader, num_epochs=10):
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters())

    for epoch in range(num_epochs):
        model.train()
        for inputs, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        model.eval()
        val_loss = 0
        with torch.no_grad():
            for inputs, labels in val_loader:
                outputs = model(inputs)
                val_loss += criterion(outputs, labels).item()

        print(f"Epoch {epoch+1}/{num_epochs}, Validation Loss: {val_loss/len(val_loader)}")

# 4. Inference
def detect_stutter(model, audio_path):
    waveform, sample_rate = torchaudio.load(audio_path)
    if waveform.shape[0] > 1:
        waveform = torch.mean(waveform, dim=0, keepdim=True)
    if sample_rate != 16000:
        waveform = torchaudio.transforms.Resample(sample_rate, 16000)(waveform)
    mel_spec = torchaudio.transforms.MelSpectrogram(
        sample_rate=16000,
        n_fft=400,
        hop_length=160,
        n_mels=64
    )(waveform)
    mel_spec = torchaudio.transforms.AmplitudeToDB()(mel_spec)
    if mel_spec.shape[2] > 1000:
        mel_spec = mel_spec[:, :, :1000]
    else:
        mel_spec = torch.nn.functional.pad(mel_spec, (0, 1000 - mel_spec.shape[2]))

    model.eval()
    with torch.no_grad():
        output = model(mel_spec.unsqueeze(0))

    return output.squeeze().numpy()

dataset = StutterDataset('/content/sampled_updated_labels_with_clips.csv')
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

num_labels = len(dataset[0][1])
model = StutterDetectionModel(num_labels=num_labels)
train_model(model, train_loader, val_loader)

result = detect_stutter(model, '/content/drive/MyDrive/Phonic Forge/Pre-Processed/IStutterSoWhat/4.wav')
print(result) # no stuttered words, Unsure, Music

df.columns

sampled_df = df.sample(n=100, random_state=42)

sampled_df.to_csv('sampled_updated_labels_with_clips.csv', index=False)

model_save_path = '/content/drive/MyDrive/Phonic Forge/Models/stutter_detection_model.pth'
torch.save(model.state_dict(), model_save_path)

model_save_path = '/content/drive/MyDrive/Phonic Forge/Models/stutter_detection_model.pth'
num_labels = len(dataset[0][1])
model1 = StutterDetectionModel(num_labels=num_labels)
model1.load_state_dict(torch.load(model_save_path))
model1.eval()

result = detect_stutter(model1, '/content/drive/MyDrive/Phonic Forge/Pre-Processed/IStutterSoWhat/4.wav')
print(result)